### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by paladox**
Test against node_js version 0.12

### CODE REVIEW

**Comment by paladox** [comment]
Ive just signed it.

**Comment by leobalter** [comment]
It would be better if node 4.1 is included.

Also: we need to run the browserstack check only on one of them, and that's the case to use in node 4.1.

**Comment by paladox** [comment]
If we do 4 it will automatically go for the latest stable 4.x release available.

**Comment by leobalter** [comment]
Without handling the browsertack runner to run on a single node environment, I can't move this on. Otherwise each CI run will overload browserstack.

**Comment by paladox** [comment]
How would I get browserstack to check only 4.1 or 4.2.

**Comment by leobalter** [comment]
@paladox Honestly I don't know a better way, which probably exists. Maybe checking if the current version (`node -v` or `process.versions.node`) is not 0.10 or 0.12.

**Comment by leobalter** [comment]
also, it would be great if you apple the [style guidelines](http://contribute.jquery.org/) on the commits

**Comment by leobalter** [comment]
We need this PR to get in shape before a next review. I'll close it for now and we can reopen it when if it gets ready again.

**Comment by mgol** [comment]
A version of this PR that runs the `browserstack` task only in one Node.js version: #997.

**Pull request closed without merging**
