### PR TITLE
HTML Reporter: Fixed the confusing Line Breaks in Diffs

### PR DESCRIPTION
**Pull request by gauravmittal1995**
Regarding https://github.com/jquery/qunit/issues/348
In the Below picture:
1st assert has same keys but different values,
2nd assert is for two strings,
3rd assert has different keys but similar values.

diff_pic

### CODE REVIEW

**Comment by gauravmittal1995** [comment]
@leobalter @jzaefferer Please Review

**Comment by jzaefferer** [comment]
Can you provide a screenshot of those same diffs without the changes of this PR applied?

**Comment by jzaefferer** [comment]
Also #348 had an example where an object was replaced by an array. Could you cover that as well?

**Comment by gauravmittal1995** [comment]
@jzaefferer for the object replaced by array:

list_array

**Comment by gauravmittal1995** [comment]
Now for without the change (i.e originally): 

pic1
pic2

**Comment by gauravmittal1995** [comment]
@jzaefferer Hey, I also tried another way and got the following diff:

new_diff1
new_diff2

Please Let me know which one according to you is better.

**Comment by jzaefferer** [comment]
Both approaches are definitely an improvement over the current implementation. The "another way" looks even better to me. We may need more tests to avoid regressions though.

@leobalter what do you think?

**Comment by gauravmittal1995** [comment]
@jzaefferer the another way uses google's diff-patch-match library.

**Comment by jzaefferer** [comment]
Ah, good to know. Could you create a separate PR for that?

**Comment by leobalter** [comment]
I liked these changes, but I would like to see this other PR as it looks better.

**Comment by gauravmittal1995** [comment]
@jzaefferer @leobalter Creating the new PR. Its taking time because have to refactor as it doesnt use cameCase and vars are scattered throughout the function. Will send it soon

**Comment by leobalter** [comment]
As it is an external library, it would be good to ignore it on jshint and jscs checks. Also, getting the code from a npm dependency would be nice.

**Comment by gauravmittal1995** [comment]
@leobalter @jzaefferer PR opened https://github.com/jquery/qunit/pull/772

**Comment by gauravmittal1995** [comment]
@jzaefferer I think its safe to close this PR as we r mostly gonna stick with https://github.com/jquery/qunit/pull/772 ??

**Comment by leobalter** [comment]
Yes, @gauravmittal1995, thanks!

**Pull request closed without merging**
