### PR TITLE
HTML Reporter: Prevent XSS attacks

### PR DESCRIPTION
**Pull request by leobalter**
Closes #728

### CODE REVIEW

**Comment by JamesMGreene** [comment]
Don't we want to clear out its `innerHTML` first?

**Comment by leobalter** [comment]
Fixed, browserstack tests passing.

**Comment by jzaefferer** [comment]
Looks good to me.

**Comment by JamesMGreene** [comment]
:+1:

**Comment by jzaefferer** [comment]
Rebased and landed.

**Pull request closed without merging**
