### PR TITLE
Build: Ignore BrowserStack generated file

### PR DESCRIPTION
**Pull request by leobalter**
BrowserStack-runner is generating this binary file to the project's root

### CODE REVIEW

**Comment by JamesMGreene** [comment]
Guessing it's from the local tunnel? Anyway, LGTM.

**Comment by leobalter** [comment]
Yes, it is.

**Comment by jzaefferer** [comment]
Let's report this on their end, instead of ignoring the issue. I've ignored it for too long myself.

**Comment by jzaefferer** [comment]
Same for that pid file.

**Comment by leobalter** [comment]
Makes sense. :+1:

**Comment by jzaefferer** [comment]
Created a ticket: https://github.com/browserstack/browserstack-runner/issues/105

**Pull request closed without merging**
