### PR TITLE
Assert: Exports raises() in the global scope

### LINKED ISSUE #883: `raises` is not exported in the global scope in QUnit pre-2.x
`Assert.prototype.raises` is an alias for `Assert.prototype.throws`, but only the latter is exported in the global scope. Example: 

```
QUnit.test( "throws & raises", function( assert ) {

  assert.throws( function() { throw "error" });  //ok
  assert.raises( function() { throw "error" });  //ok

  throws( function() { throw "error" });  //ok
  raises( function() { throw "error" });  //ReferenceError: raises is not defined
});
```

### PR DESCRIPTION
**Pull request by scinos**
Fixes #883

### CODE REVIEW

**Comment by berkerpeksag** [comment]
According to https://github.com/jquery/qunit/pull/577 and https://github.com/jquery/qunit/issues/563, `throws` and other assertion methods will be removed in 2.0.

**Comment by leobalter** [comment]
@berkerpeksag, QUnit 2.0 will not remove any current assertions, but will stop exposing them to the global scope.

They are not many, you can see a list [from the docs](http://api.qunitjs.com/category/assert/).

Other methods like `test` and `module` will also stop being exposed to the global scope, you will be able to call them from the QUnit object.

As you can already do today, on QUnit 2.0 you will need to get a reference from the assert object inside the test function:

```js
// before
test(function() {
  ok( true );
});

// now and after
var test = QUnit.test;

test(function( assert ) {
  assert.ok( true );
});
```

**Comment by leobalter** [comment]
@scinos, `raises` is just an alias for `throws` to solve a compatibility problem on narwhal and Closure Compiler envs. See #675 

It is not exposed as a global and I'm not sure if we should do it, that would be one more thing to deprecate before 2.0.0 (we are almost there). It might also pollute the global scope and maybe even conflict on other projects.

The code is fine. I just want another PoV from @jzaefferer or @gibson042 to confirm if we should do it.

Meanwhile, would you [sign the CLA](https://github.com/jquery/qunit/pull/884#issuecomment-150880116)?

**Comment by gibson042** [comment]
This function/method pair has quite a sordid [history](https://github.com/jquery/qunit/blob/master/History.md):
* 1.0.0 introduces `QUnit.raises` and global `raises`
* 1.9.0 deprecates `QUnit.raises` and global `raises` in favor of `throws` equivalents
* 1.13.0 replaces `QUnit.raises` and global `raises` functionality with failed-assertion generators
* 1.15.0 removes `QUnit.raises` and global `raises`
* 1.16.0 reintroduces `QUnit.raises`

I don't like the global functions at all, but I like the inconsistency less. I think we should land this, completing 1.16.0's partial restoration.

**Comment by leobalter** [comment]
You're right.

@scinos, The changes are good, we only need you to sign the CLA so I can merge this.

**Comment by scinos** [comment]
@leobalter I signed the CLA a couple of times, but it still says I need to sign it. Not sure what I'm doing wrong.
The email address of my GitHub account doesn't match the email address in the commit. Could that be the problem?

**Comment by leobalter** [comment]
The CLA does not check anything on your Github acc, only the name and email used on the commits.

If you check on the [link](http://contribute.jquery.org/CLA/status/?repo=qunit&sha=c55d76a08b49a9a3e81cd211558bd95d80085563) provided by the jQueryBot, you can see if they match with the info you used to sign the CLA. 

If you want to change the name or email on your commit, the link provides a follow through, or an easy way as you only have one commit on this branch:

```sh
$ git commit --amend --author 'name last_name <email@email.com>'
```

**Comment by leobalter** [comment]
after that you can send a forced push with a `+` before your branch name. On this PR you're using your master branch, so that would be:

```sh
$ git push origin +master
```

**Comment by leobalter** [comment]
I can see you changed the email at the [CLA check](http://contribute.jquery.org/CLA/status/?repo=qunit&sha=5e74ee1bfb70efa9a3224c91d810216bc293ff91). 

I don't have access to the CLA document, but if you confirm you already signed it with the same info, we might have some unexpected bug.

**Comment by scinos** [comment]
Yep, I signed it with both emails several times, and still no luck.
I'm trying with different browsers and a clean session, to see it that helps. If not, I'll send an email to license@jquery.com to report the problem.

**Comment by leobalter** [comment]
@jzaefferer would you help me here?

**Comment by scinos** [comment]
I sent an email to license@jquery.com with all the details but Gmail says that account does not exist :(

**Comment by jzaefferer** [comment]
@scinos sorry for the trouble with the CLA. Your first signature matched your commit, the others didn't change anything. I haven't yet figured out why the script still thinks this PR is invalid.

**Comment by jzaefferer** [comment]
I ran the audit script manually, that helped.

**Comment by leobalter** [comment]
Thanks, @scinos! It's merged at 67727bc.

**Pull request closed without merging**
