### PR TITLE
Update ignoreGlobalErrors only if this.test is defined

### PR DESCRIPTION
**Pull request by mdartic**
I have some tests failing around these lines since 1.17.1 (before I was in 1.14.0).

Changing these lines made my tests work again.

### CODE REVIEW

**Comment by JamesMGreene** [comment]
Could you please show us an example test that is causing this issue?

Are you using global assertion references (e.g. `notEqual` and/or direct references on the `QUnit.assert` object (e.g. `QUnit.assert.notEqual`) rather than local instantiated references? e.g.

```js
QUnit.test("blah", function(localAssert) {
  localAssert.notEqual(true, false, "foobar");
});
```

Any which way should be fine and supported in the `1.x` series, so this sounds like a regression. However, you should be aware that only the loral assertion reference style will be supported in the upcoming `2.x` series.

**Comment by mdartic** [comment]
Well, I've create this repo to test it : https://github.com/mdartic/qunit_752

And, indeed, I use direct references on the QUnit.assert...

We plan to integrate the local assertion in our tests, but for the moment we have a lot 'direct' style.

**Comment by JamesMGreene** [comment]
How about if you use the global references? e.g.

```js
QUnit.test("If I use global assertions, it _____?", function() {
    expect(2);

    deepEqual(isNotNull('pouet'), true);
    
    throws(function () {
        isNotNull(null);
    });
});
```

**Comment by mdartic** [comment]
I've update the test and... well, you're right !

I let you see if it's a good thing to integrate the check of 'this.test'.

Thanks for your help.

**Comment by leobalter** [comment]
@mdartic, [QUnit.assert.push](https://github.com/jquery/qunit/blob/master/src/assert.js#L46) makes a test reference to the current running test when it's not present. It doesn't break the other assertions because they basically just call that method, but that doesn't happen on `QUnit.assert.throws`.

The fail is present at this [JSBin example](http://jsbin.com/quvupolaso/1/edit?js,output) where it fails when using the `QUnit.assert.throws` directly.

```js
function throwSomething() {
  throw 'something';
}

QUnit.test("Throw tests", function( assert ) {
    assert.throws(throwSomething);
    throws(throwSomething);
    QUnit.assert.throws(throwSomething);
});
```

Instead changing the method behavior, `throws` should get the same current test reference as `push` at this line:

```js
var assert = this,
    currentTest = ( assert instanceof Assert && assert.test ) || QUnit.config.current;
```

and use `currentTest` instead of `this.test`

**Comment by jzaefferer** [comment]
Whatever the underlying issue, the proposed fix isn't acceptable. At best it hides an error, but doesn't actually solve it.

Please file a new issue if the problem persists.

**Pull request closed without merging**
