### PR TITLE
Build: Update JSCS and JSHint

### PR DESCRIPTION
**Pull request by trentmwillis**
Addresses #879 since it didn't appear to be moving along. Little style issues sure do build up over time.

### CODE REVIEW

**Comment by leobalter** [comment]
`npm test` is failing on my machine probably by other reasons (running from a new environment on Windows 10 with the newest version of Node).

I'll need more time before I merge this to get back to my original env and see if this branch works and potentially file an issue to fix QUnit development on Windows 10/node.

**Comment by trentmwillis** [comment]
Okay, sounds good. Do you think it'd be worthwhile at all to look into integrating something like [AppVeyor](https://www.appveyor.com/) into the project? Would help us verify things work with Windows environments.

**Comment by leobalter** [comment]
It's an extra CI step that I wouldn't mind to have. This would allow tests for node-chakra as well, eventually.

**Comment by leobalter** [comment]
It works here, and on Node 4 to 5.7.0 too.

I'll check what is happening on Windows on another issue

**Pull request closed without merging**
