### PR TITLE
Spelling fixes

### PR DESCRIPTION
**Pull request by jsoref**
Sorry, this is the same as pr#897, the tool I was using accidentally let me eat my branch marker which closed it...

### CODE REVIEW

**Comment by leobalter** [comment]
It's weird there's no hooked CLA checking here. 

cc @jzaefferer

**Comment by jsoref** [comment]
@leobalter: you probably lost a race w/ @jquerybot

**Comment by leobalter** [comment]
Ok, we've got a timeout delivering the CLA hook, it's working now and the CLA is verified. 

I'll squash and merge this soon, thanks @jsoref!

**Comment by leobalter** [comment]
> you probably lost a race w/ @jquerybot

I had to trigger the *Redeliver* button on the project settings and it saved everything! :)

**Pull request closed without merging**
