### PR TITLE
HTML Reporter: Filter as you type

### PR DESCRIPTION
**Pull request by gauravmittal1995**
Currently, the filter needs to be submitted (Enter or clicking on "Go") for it to filter the results.
This adds the event of filtering as soon as you start typing in the textbox.

### CODE REVIEW

**Comment by leobalter** [comment]
I have a concern here where this feature might break accessibility.

**Comment by gauravmittal1995** [comment]
@leobalter Hey, did u test this out??

**Comment by leobalter** [comment]
I'm still looking at the older PRs to see what can be merged.

**Comment by jzaefferer** [comment]
I don't like this idea. Why would I want it to rerun tests for every character I type? Also introducing more URL params solely for tracking keyboard focus is quite questionable as well.

**Comment by jzaefferer** [comment]
Closing this for now. Can reopen if my previous questions are answered.

**Pull request closed without merging**
