### PR TITLE
Update grunt-jscs to 2.2.0

### PR DESCRIPTION
**Pull request by paladox**
Update grunt-jscs to 2.2.0

### CODE REVIEW

**Comment by leobalter** [comment]
Would you mind to use a single PR the commits on  #888, and #889?

We can still handle the travis changes on the #887, but the other PRs refers both to npm dependencies.

**Comment by leobalter** [comment]
Btw, why it's not grunt-jscs 1.8.0 anymore?

**Comment by paladox** [comment]
1.8.0 was failing. So upgrading to 1.1.0

**Comment by leobalter** [comment]
If it is failing, we need to make it pass. Otherwise, there is no value to upgrade it to an older version than the last one.

**Comment by paladox** [comment]
Ive updated it to 2.2.0 instead.

**Comment by jzaefferer** [comment]
Regarding the CLA check: You've commited with a "paladox@users.noreply.github.com" as the email address, which we can't accept for the CLA. You can find instructions on updating your git email address, even for existing commits, here: http://contribute.jquery.org/CLA/status/?repo=qunit&sha=922362d0ff2678bafd56535eda48ec3057c3fbef#updating-git-config

As for the actual change: Newer jscs versions include more checks for the jQuery preset, so there's now a lot of failures. Fixing those would make this change quite valuable! Using jscs's `-x` parameter can help fixing a lot of the spacing issues.

**Comment by paladox** [comment]
Hi I hide my email on GitHub using the hide your email feature. I correctly added my email but isent detecting it.

**Comment by paladox** [comment]
Is there any way to do it online and verify it manually.

**Comment by leobalter** [comment]
You should run Grunt on your machine to get the errors report. Also, you can save your files and don't need to create a commit for every change.

**Comment by leobalter** [comment]
We need this PR to get in shape before a next review. I'll close it for now and we can reopen it when if it gets ready again.

**Pull request closed without merging**
