### PR TITLE
Build: Introduce AppVeyor for Windows CI

### PR DESCRIPTION
**Pull request by trentmwillis**
Introduces a simple AppVeyor config to enable Windows CI as discussed in #943.

Edit: Unfortunately, looks like it won't actually do an AppVeyor build until after the config has been committed.

### CODE REVIEW

**Comment by leobalter** [comment]
Do we need to setup anything on AppVeyor before?

**Comment by trentmwillis** [comment]
I've already enabled it and ran one build (which failed since there is no configuration). After merge it should run for all PRs/merges.

**Comment by leobalter** [comment]
It's merged. Let's see how it goes! :+1:

**Comment by leobalter** [comment]
It worked just fine! That's great!

**Pull request closed without merging**
